### ISSUE TITLE
nav-mesh component is not exported into GLTF

### ISSUE THREAD

**Issue by rawnsley** [MozillaReality/hubs-blender-exporter#10]
Adding the nav-mesh component to a node doesn't lead to the extension being added to the GLTF output. This may be due to a [bug with empty extension properties](https://github.com/KhronosGroup/glTF-Blender-IO/issues/870) in the exporter.

[One proposed workaround](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1103) is to add a dummy property. It certainly appears to fix the problem when I tested it by changing default-config.json

**Comment by netpro2k** [comment]
Components with no properties are now handled correctly without the need to manually add a dummy property.
