### ISSUE TITLE
Morph Audio Feedback component in Blender 3.2 makes exported model unrenderable in Hubs

### ISSUE THREAD

**Issue by bxbrenden** [MozillaReality/hubs-blender-exporter#102]
## Description
A model that is exported with the Blender Hubs add-on works as expected until a `Morph Audio Feedback` component is added. Initially, the model is rigged using the [avatar base blend file](https://github.com/MozillaReality/hubs-avatar-pipelines/blob/master/Blender/AvatarBot/AvatarBot_base_for_export.blend). The default gLTF export settings are used, and the avatar can be used in Hubs.

Once the audio-morph-feedback component is added to the mesh and exported to a `.glb` file with default export settings, the object is unrenderable in Hubs. If you choose it as your new avatar, you will be invisible in the scene. If you drag and drop it into the Hubs window, it turns into a "loading cube", a multicolored cube with orbiting particles and never changes.

### Steps to reproduce the expected behavior:
1. Open the attached `Duckman-01-WITHOUT-shape-key.blend` file with Blender `3.2.2` and version `1.0.0 Beta 2` of the Hubs Blender Add-on. **Note**: all example files are in the `Duckman-Example-Files.zip` archive attached at the end of this report.
2. Select the skeleton, Duckman mesh, and plain-axes empty in the 3D viewport (object mode).
3. Go to `File` -> `Export` -> `gLTF 2.0 (.glb/.gltf)`.
4. Keep the default settings and export your file under whatever name you like. Alternatively you can use the attached `Duckman-Hubs-Renderable.glb`.
5. Drag and drop the `.glb` file into an active Hubs window. The character should render as a small 3d representation of Duckman.

### Steps to reproduce the unexpected behavior
1. Repeat steps 1-5 from above, only using `Duckman-02-WITH-shape-key.blend` for step 1 and `Duckman-Hubs-Unrenderable.glb` for step 5. When you do, the result should be unrenderable in Hubs. 

The only differences between the two attached blend files are:
- I added a shape key with the beak slightly opening
- I added a Morph Audio Feedback component to the main avatar mesh and referenced the shape key

## Expected behavior
An exported `.glb` file with a Morph Audio Feedback component should produce a 3D file that is renderable in Hubs and which has a shape key that gets modified by a mic's audio levels.

## Screenshots
![Render-vs-No-Render](https://user-images.githubusercontent.com/26355516/183800534-74f2cb1d-fb47-4132-bc6e-26656c3604d7.png)
Screenshot notes: unrenderable object is the cube on the left. Renderable object is the duck on the right.

## Hardware
 - Add-on Release Version: `1.0.0 Beta 2`
 - Blender Version: `3.2.2`

## Additional context
[Duckman-Example-Files.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/9296184/Duckman-Example-Files.zip)

**Comment by Exairnous** [comment]
I think this is because you're using `Apply Modifiers` when exporting.  Apply Modifiers prevents shape keys from exporting (this is mentioned in the tooltip when you hover over that option), so when it gets into Hubs the shape key referenced by the Morph Audio Feedback component isn't there and this causes an error.  So I think this is an issue on the Hubs Client side and not the exporter.

If you want to apply the modifiers manually before exporting, take a look at this (the manual way):
https://blender.stackexchange.com/questions/155930/cant-apply-modifiers-with-shapekeys-on-blender-2-8

Or you can try this add-on (I haven't tested it myself, but it looks nice):
https://github.com/smokejohn/SKkeeper (YouTube video on how to use it: https://www.youtube.com/watch?v=Bvav2lV6838)

<details>
<summary>This is the error I found in the browser console:</summary>

```javascript
Uncaught (in promise) TypeError: e.morphTargetDictionary is undefined
    morphs audio-feedback.js:211
    init audio-feedback.js:211
    Aframe 7
        initComponent
        updateProperties
        Component
        n
        value
        value
        value
    Os gltf-model-plus.js:72
    e gltf-model-plus.js:273
    As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    promise callback*As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    Is gltf-model-plus.js:240
    traverse three.module.js:8130
    traverse three.module.js:8136
    traverse three.module.js:8136
    traverse three.module.js:8136
    Is gltf-model-plus.js:240
    As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    applySrc hub-7e396681a57e454c9d10.js:1
    applySrc gltf-model-plus.js:827
    As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    promise callback*As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    promise callback*As hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    ks hub-7e396681a57e454c9d10.js:1
    applySrc gltf-model-plus.js:770
    update gltf-model-plus.js:750
    Aframe 7
        initComponent
        updateProperties
        Component
        n
        value
        value
        value
    update media-loader.js:557
    Eo hub-7e396681a57e454c9d10.js:1
    a hub-7e396681a57e454c9d10.js:1
    _o hub-7e396681a57e454c9d10.js:1
    _o hub-7e396681a57e454c9d10.js:1
    update media-loader.js:323
    Aframe 4
        callUpdateHandler
        updateProperties
        value
        value
    Or media-utils.js:219
    promise callback*Or media-utils.js:216
    t scene-entry-manager.js:216
    _setupMedia scene-entry-manager.js:320
    i raven.js:332
```

</details>

**Comment by bxbrenden** [comment]
@Exairnous thanks for quick reply. You were exactly right! The `Apply Modifiers` setting is checked by default in the gLTF export tool. Once I unchecked it and re-exported, I got a Duckman avatar that reacted to audio by opening his beak as expected :heavy_check_mark:.

I'll go ahead and close issue, as you've solved my problem. Thanks again!

**Comment by Exairnous** [comment]
You're welcome. :slightly_smiling_face:
