### ISSUE TITLE
Blender 'model' component scale off.

### ISSUE THREAD

**Issue by karunakaruna** [MozillaReality/hubs-blender-exporter#104]
**Description**
A .glb referenced in a blender scene using the model-component comes in very small. An empty with a model-component must be scaled 10,000x to be the correct size in scene, for example.

**To Reproduce**
Create a 2m cube in blender. 
Export box to .glb.
Upload .glb to github or wherever - generate link.
Create a scene with a 2m cube for reference.
Create empty in scene and add model-component - reference url to 2m cube .glb.
Duplicate this empty, and scale to 10,000 in all directions. 
Export scene to .glb and view in hubs. 
The cube will be so small it is not visible.
The scaled cube will be the correct size.

**Expected behavior**
A object exported as a .glb should import at the correct size when imported using a model-component on a 1x1y1z empty.

**Screenshots**
![blender_2022-08-19_13-01-04](https://user-images.githubusercontent.com/20630604/185698138-63afaabe-7d40-41ec-9441-5a0b98a8f133.png)

**Hardware**
 - Add-on Release Version: 1.0.0b
 - Blender Version: 3.2

**Additional context**

*Scene Links, models, any other helpful context*
Scene: https://github.com/karunakaruna/memory/blob/main/Hubs_Scale.blend
2m cube model: https://raw.githubusercontent.com/karunakaruna/memory/main/cube.glb

**Comment by keianhzo** [comment]
This also happens if you load a model with the link component.

**Comment by keianhzo** [comment]
This will most likely be fixed on the client side. Keeping it opened for tracking purposes.
