### ISSUE TITLE
Blender 3.3 doesn't export environment settings if .hdr images aren't used.

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#112]
**Description**
Blender 3.3 doesn't export the Environment Settings component properly if an image type other than HDR is used as either the background or the environment map.

**To Reproduce**
- Add the Environment Settings component to the scene.
- Set the `Background` property to a jpg.
- Set the `EnvMap` property to a .hdr.
- Export to glTF.
- Check the exported glTF and see that the Environment Settings component is missing, or load it into a Hubs room and see that the background is black and there is no environment map.

**Expected behavior**
The Environment Settings component should export.

**Hardware** 
 - Add-on Release Version: 1.0.0 beta 4
 - Blender Version: 3.3.0

**Comment by theanine3D** [comment]
I just encountered this issue myself. Converting the skybox from PNG to HDR fixed the issue as a temporary workaround. Hope this issue is fixed as HDR format caused a dramatic multiplication of the file size. 😲

**Comment by keianhzo** [comment]
I think this should have been fixed by the latest beta 6 release https://github.com/MozillaReality/hubs-blender-exporter/releases/tag/v1_0_0b6 Can you confirm?

**Comment by Exairnous** [comment]
Works for me on the latest master.
