### ISSUE TITLE
Old architecture components aren't migrated when appending/linking.

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#119]
**Description**
Components from files saved in the old architecture aren't migrated to the new architecture when appending or linking, and some don't delete properly (when you try to remove them it causes a Python error and the Audio Params components will be left behind).

**To Reproduce**
- Open Blender to a new file.
- Append or link in a component that needs migration (such as a Media Frame or Loop Animation component).
- See that it hasn't been migrated properly, e.g. Media Frames are rotated 90 degrees, no tracks are present in the Loop Animation component, or there is no Networked component.

**Expected behavior**
Appended objects should have their data migrated if they were created with the old architecture.

**Hardware** 
 - Add-on Release Version: 1.0.0 beta 4
 - Blender Version: 3.3.0, 3.2.2, 2.93.9

**Additional context**
Python error when trying to remove a non-migrated component:
```
Python: Traceback (most recent call last): 
  File "/home/ryan/.config/blender/2.93/scripts/addons/io_hubs_addon/components/operators.py", line 178
, in execute 
    remove_component(obj, self.component_name) 
  File "/home/ryan/.config/blender/2.93/scripts/addons/io_hubs_addon/components/utils.py", line 42, in 
remove_component 
    remove_component(obj, dep_name) 
  File "/home/ryan/.config/blender/2.93/scripts/addons/io_hubs_addon/components/utils.py", line 35, in 
remove_component 
    del obj[component_class.get_id()] 
KeyError: 'property not found in group'
```

**Comment by keianhzo** [comment]
Already addressed
