### ISSUE TITLE
Pre/post export hooks don't loop through all objects.

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#126]
**Description**
The pre/post export hooks currently loop through the current view layer's objects instead of all the objects in the blend file.  This can cause problems with export because the glTF exporter doesn't use view layers as a determining factor when exporting objects and may also be exporting multiple scenes, so some of the objects exported may not have the hooks applied.

**Expected behavior**
The pre/post export hooks should loop through all the objects in the blend file.

**Hardware** 
 - Add-on Release Version: 1.0.0 beta 4
 - Blender Version: N/A

**Comment by keianhzo** [comment]
Already addressed
