### ISSUE TITLE
UV map texture animation?

### ISSUE THREAD

**Issue by poVoq** [MozillaReality/hubs-blender-exporter#13]
Would it be possible to support a texture animation like shown in this Blender tutorial?

https://youtu.be/5NlvgMYZgaY

Booth for looping some eye movement / blinking and maybe also for voice modulation?

Thanks for looking into that :)

**Comment by poVoq** [comment]
https://youtu.be/0lfyO0wXOQw

This would also work on partial textures of avatars?

At least for looping eye motion that would work I guess.

But some way to trigger this from audio input would be great for mouth movement.

**Comment by netpro2k** [comment]
This should actually be possible now with the `uv-scroll` component. See https://www.youtube.com/watch?v=0pCGswUlrfk
