### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by hollyhudson** [MozillaReality/hubs-blender-exporter#16]
It would be helpful to have installation instructions in the readme so that folks know to download the zip file, click install in the preferences, and choose the zip file from the file browser.  This was only the second addon I installed in Blender and it's been a while since I installed the first one, so I had forgotten what to do and it took a while to figure it out.

**Comment by matthewbcool** [comment]
Some screenshots for the instructions:
<img width="591" alt="download the source zip of the latest release" src="https://user-images.githubusercontent.com/4493657/102955067-e8179500-4489-11eb-9f26-c764dfa1e4dc.png">
<img width="780" alt="in Blender prefs install addon" src="https://user-images.githubusercontent.com/4493657/102955927-dcc56900-448b-11eb-8bfa-07e68b31cffd.png">
<img width="494" alt="hubs blender exporter installed" src="https://user-images.githubusercontent.com/4493657/102957622-bd303f80-448f-11eb-812a-0167003e0ce7.png">
