### ISSUE TITLE
Dynamic shadows missing

### ISSUE THREAD

**Issue by garyritchie** [MozillaReality/hubs-blender-exporter#189]
**Description**
Shadow maps are not rendered when uploading glb scene to hubs.
**To Reproduce**

1. Add Cube with Shadow component with cast and receive enabled
2. Add Plane with Shadow component with receive enabled
3. Add directional, spot, or shadow light component to an empty

**Expected behavior**
I expect any of these dynamic lights to not just light the scene but also cast a shadow with the default settings provided.

**Screenshots**

**Hardware** 
 - Add-on Release Version: https://github.com/MozillaReality/hubs-blender-exporter/pull/187/commits (f85e6315b9d06208bcd16fa494b80ea198ca46f8) 3d gizmos WIP, but also had been using a build (12/11) from master.
 - Blender Version: 3.3.2 linux

**Additional context**

- Scene: https://hubs.mozilla.com/qQqE8Dp
- Blend: [test_lighting.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/10254553/test_lighting.zip)
- Glb: [test_lighting.glb.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/10254560/test_lighting.glb.zip)

**Comment by garyritchie** [comment]
Seems to be an issue specific to Chrome.

Dynamic shadow and lighting/color differences -- Pictured left: Google Chrome 108.0.5359.94 (Official Build) (64-bit) and on the right: Firefox 108.0.1 (64-bit)

![Screenshot from 2022-12-19 10-48-20](https://user-images.githubusercontent.com/853094/208465618-2bf28da5-c338-490f-98dc-6531b3ba681e.png)

settings...
![Screenshot from 2022-12-19 10-51-41](https://user-images.githubusercontent.com/853094/208466072-ea5c08f8-e0df-4311-b219-c4e441e5333c.png)

Blend and Glb for good measure...
[test_lighting2.blend.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/10260715/test_lighting2.blend.zip)
[test_lighting2.glb.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/10260716/test_lighting2.glb.zip)

**Comment by matthewbcool** [comment]
Should we convert this issue to a Hubs client chrome specific one? Thanks for this excellent report and documentation. 🙂

**Comment by garyritchie** [comment]
Sure, that would be fine. Either way, it should help save other's time when encountering browser differences.
