### ISSUE TITLE
Waypoint components need to be networked if they `canBeOccupied`.

### ISSUE THREAD

**Issue by johnshaughnessy** [MozillaReality/hubs-blender-exporter#19]
Discord user mbcool reported this issue with waypoint components:

https://discord.com/channels/498741086295031808/537726109555359745/791100552989245450

The fix may be to check if the `waypoint` component `canBeOccupied`, and add a `networked` component with a unique ID in that case:
https://github.com/MozillaReality/hubs-blender-exporter/blob/83a76478363e4644f6baea04a365bada9c17d351/__init__.py#L162

We might even skip the check for `canBeOccupied` and simply add a `networked` component to each waypoint even if it does not need it.

I am guessing this will break if a user loads multiple copies of the same gltf file into the hubs room because the `networked` `id` is the same between them, but that is not unique to this issue and should be addressed separately.

**Comment by matthewbcool** [comment]
Added "waypoint" to the check and tried loading three instances of the same blender exported cube waypoint component both loading in spoke and in a room. There was a moment when I was not able to occupy a waypoint while another avatar occupied a different instance but I was unable to reproduce that. 

https://user-images.githubusercontent.com/4493657/104833076-f7042400-584a-11eb-8a7e-ab876a8e9a29.mp4

Fun side design discovery: Metal Gear Solid mode:

https://user-images.githubusercontent.com/4493657/104833060-e3f15400-584a-11eb-92e2-086451fabdee.mp4

**Comment by rawnsley** [comment]
@netpro2k [mentioned network ID assignment](https://github.com/MozillaReality/hubs-blender-exporter/pull/11#issuecomment-743476315) previously. It looks like it will be done automatically by the Hubs client in future, which makes more sense.

**Comment by keianhzo** [comment]
This has been fixed already
