### ISSUE TITLE
Fog depth calculation causes screen periphery to have less fog.

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/hubs-blender-exporter#201]
**Description**
Because of how the depth is calculated, all fog types (linear/exponential) cause the edges of the user's field of view to have less fog than expected. This is common in older games, for example, where the depth is calculated as a straight line instead of a curve.
Arguably not a bug in the strict sense, but the symptom is something that some users have pointed out as a problem.

**To Reproduce**
1. Make a new room.
2. append the URL parameter: `?debugLocalScene` and reload the page.
3. Drag/drop[ this test scene asset](https://github.com/mozilla/hubs-sample-assets/blob/main/Hubs%20Components/Exported%20GLB%20Models/Fog.glb) into the webpage.
4. After the scene loads, try rotating your camera.
5. Result: things along the edges are more visible (less foggy) than they should be, including the large distant text that should remain illegible when standing in the yellow circle.

**Expected behavior**
Fog should remain a consistent density at all angles from the camera.

**Screenshots**
![image](https://user-images.githubusercontent.com/31968496/219172949-e3fdf360-48ed-443d-a740-5d96442bf2fb.png)

![image](https://user-images.githubusercontent.com/31968496/219173095-dd248494-1062-40f9-b579-75f62fe26b33.png)

**Hardware** 
 - Add-on Release Version: 1.0.0.72
 - Blender Version: 3.3.1, 3.4.1

**Additional context**
This article explains the problem and how to avoid it:
https://www.tomlooman.com/unreal-engine-distance-fog-material/

**Comment by keianhzo** [comment]
All valid points but this is not really related to the Blender Add-on. I'll open this same report in the Hubs client repo.
