### ISSUE TITLE
2.91 Lightmap only visibe when materials set to low

### ISSUE THREAD

**Issue by TheBricktop** [MozillaReality/hubs-blender-exporter#21]
Browser :
Android mobile - Chrome 
Edge & Firefox PC Windows
Chrome & Safari - MacOS 

Currently there is no way to preview baked lightmaps on material setting to high.
Seems like lightmaps arent displayed in high def materials by design, but lightmaps have additional effects that even high quality materials in hubs cant provide (Emissive materials or light transmission for example). 
Better way to tackle this problem would be a tick box in misc preferences alowing the lightmaps to be seen.

**Comment by dcjweller** [comment]
My lightmap is still not appearing when materials set to low. It appears in Spoke, but not in Hubs

**Comment by keianhzo** [comment]
This should be fixed now. Please reopen otherwise providing an example Blender file.
