### ISSUE TITLE
Blender 3.6 export hook failures.

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#225]
**Description**
In Blender 3.6 these errors are appearing in the console when trying to export as glTF.
```
gather_material_hook fails on <io_hubs_addon.io.gltf_exporter.glTF2ExportUserExtension object at 0x7f15ef9c9de0> 
cannot import name 'gltf2_blender_gather_materials' from 'io_scene_gltf2.blender.exp' (unknown location) 
gather_material_hook fails on <io_hubs_addon.io.gltf_exporter.glTF2ExportUserExtension object at 0x7f15ef9c9de0> 
cannot import name 'gltf2_blender_gather_materials' from 'io_scene_gltf2.blender.exp' (unknown location)
```

**To Reproduce**
1. Export the default scene.
2. Check the console.

**Expected behavior**
The export hooks shouldn't fail.

**Hardware** 
 - Add-on Release Version: 1.1.1
 - Blender Version: 3.6

**Comment by keianhzo** [comment]
Already merged, will be available for 1.2.0
