### ISSUE TITLE
Blender won't start after addon installation

### ISSUE THREAD

**Issue by MathisPr** [MozillaReality/hubs-blender-exporter#239]
**Description**
I installed the Hubs Blender addon 1.2.0.190 with Blender 3.6.2. It works fine when i start blender, install it and then work in the session. But when i close Blender and start it again, it won't start as long as the addon is installed. Blender starts loading but then it closes after half a sec without an error message. Even when i deactivate the addon. Only option to start blender is with the "blender_factory_startup".  When i start blender with the blender_factory_startup and uninstall the Hubs Blender addon, blender starts afterwards without problems.   

**To Reproduce**
Install the addon with Blender 3.6.X and restart Blender. 
But i'm sure it is not that simple.. There must be an issue with my system.
I'm not sure but the problem started with the latest blender update from 17.08. Blender 3.6.2 **LTS** Maintainance Release.

**Expected behavior**
Blender starts with the addon installed.

**Screenshots**

**Hardware** 
 - Add-on Release Version: Hubs Blender addon 1.2.0.190
 - Blender Version: Blender 3.6.2
I tried the steam version and the download version (here i tried 3.3.10, 3.6.0, 3.6.1, 3.6.2).
 I use Win11 (22H2).

**Additional context**
*Scene Links, models, any other helpful context*

**Comment by Exairnous** [comment]
Hi, I'm sorry to hear you're having this issue.
Does this happen with previous versions of the Hubs Blender add-on or just 1.2?  Also, you mention that the problem started with the Blender 3.6 update, but now the add-on crashes previous versions of Blender as well, is that correct?  Can you try resetting one of the Blender versions you've tested to factory settings and then re-enable the Hubs add-on and see if that fixes the issue?  If the issue still persists, can you run `blender_debug_log.cmd` and `blender_debug_gpu.cmd` (these are found in Blender's installation directory) in a terminal (command prompt, powershell, etc.) and post the output from the commands here?

**Comment by MathisPr** [comment]
I tested differnt kind of Blender Versions with factory settings (i used "Load Factory Settings" in the File Menubar). 
Same again. Blender starts, i install the hubs addon, restart blender, blender won't open, i remove the hubs addon, blender starts normally.
There is a reference to mtree but i uninstalled that addon. Same result.
A mystery...
[logs blender hubsaddon.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/12412041/logs.blender.hubsaddon.zip)

**Comment by Exairnous** [comment]
Thank you for the information and sorry for the late reply.  I have an idea about what could be causing this bug, so can you try installing this test version and see if the issue persists?  (Note: this test may cause issues with the auto migrations when appending/linking in certain situations, so you probably shouldn't use it on any production files to be safe)
[io_hubs_addon_issue_239_test_01.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/12509078/io_hubs_addon_issue_239_test_01.zip)

**Comment by MathisPr** [comment]
Hi, sorry fo the late reply. I tested the test version and it seems to work without any problems. After installation I restarted Blender 3 times successfully. What ould be the next steps?

**Comment by Exairnous** [comment]
No worries, I took much longer to reply to you than you did to me.
I'm glad it's working.  So that means this issue is caused by one of the handlers running when it shouldn't in the undefined state while a file is still loading.  I've tweaked the guard on the handler so it should hopefully avoid this better.  Can you please test this new version?  If it works then I'll make a PR for this and add it to the next bugfix release.
[io_hubs_addon_issue_239_test_02.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/12518905/io_hubs_addon_issue_239_test_02.zip)

**Comment by MathisPr** [comment]
Again, sorry for the late reply. The Version 239_test_02 seems to work as well, that you very much!

**Comment by Exairnous** [comment]
No worries!  Thanks for confirming the fix and I've submitted it as PR.
