### ISSUE TITLE
Sound emitted from the Audio component emanates from the world origin when Visible is FALSE.

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/hubs-blender-exporter#240]
**Description**
When placing an Audio component on a Blender empty, the sound emanates from the world origin (0, 0, 0) instead of the location of the empty object. This occurs when the Visible component is added and set to FALSE (not visible).

**To Reproduce**

1. Make an Empty in Blender.
2. Move the Empty to a new location, preferably far from the world origin.
3. Attach an Audio component and reference an audio file.
4. Attach a Visible component and set it FALSE.
4. Export as .glb
5. Run the scene in Hubs and notice the location of the sound is incorrect.

**Expected behavior**
The audio should emanate from the object it is attached to, regardless of visibility.

**Hardware** 
 - Add-on Release Version: 1.2.0.090
 - Blender Version: 3.6.1

**Additional context**
Included are two identical exports, except for the Visible component set to TRUE versus FALSE.
[AudioTest_Visible.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/12543756/AudioTest_Visible.zip)

**Comment by keianhzo** [comment]
Closed by https://github.com/mozilla/hubs/pull/6463
