### ISSUE TITLE
Some web url links aren't working in the Link Component

### ISSUE THREAD

**Issue by MechanicalWhispers** [MozillaReality/hubs-blender-exporter#291]
**Description**
I noticed that some web links are no longer working in the Link Component, when they were working before, without changing or updating any files.

**To Reproduce**
Create a new Blender scene with two empty plain axes. Assign the Hubs Link Component to each, and input a different web url to each. I was using "https://www.apple.com" and "https://www.patreon.com". When that scene is exported to Hubs, or tested using debugLocalScene, the Patreon link shows as "Broken Media Link". But the Apple link is fine. I needed this for my Patreon, so that's why I noticed it with Patreon specifically. I tried this with and without the NewLoader and the same broken link appears both ways.

**Expected behavior**
Both Link components should show the website thumbnail, and they have previously.

**Screenshots**
![LinkComponent](https://github.com/MozillaReality/hubs-blender-exporter/assets/25749313/3fcfa016-a3e8-4d39-9f0a-938a40a32694)

**Hardware** 
 - Add-on Release Version: 1.5.0.347
 - Blender Version: 3.6.4

**Additional context**
This is a simple test file that shows the Link Component broken.
[Test.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/15418326/Test.zip)

**Comment by keianhzo** [comment]
This doesn't seem to be related to the add-on itself and some bug on [Nearspark](https://github.com/MozillaReality/nearspark) when generating some thumbnails. For some reason it chokes on https://www.patreon.com
