### ISSUE TITLE
Lightmaps are duplicated on export when referenced by multiple materials

### ISSUE THREAD

**Issue by rawnsley** [MozillaReality/hubs-blender-exporter#41]
In [this example project](https://github.com/LearnHub/HubHenge) there are three materials that share a common HDR lightmap. The GLTF export contains the same HDR file three times, which is obviously inefficient:

```
   28630 23 Sep 08:41 hubhenge.gltf
  873692 23 Sep 08:41 hubhenge_data.bin
 1517504 23 Sep 08:41 hubhenge_img0.bin
 3085418 23 Sep 08:41 hubhenge_img1.bin      <----
   16302 23 Sep 08:41 hubhenge_img10.png
 3085418 23 Sep 08:41 hubhenge_img11.bin     <----
 4613777 23 Sep 08:41 hubhenge_img12.png
  236837 23 Sep 08:41 hubhenge_img13.jpg
  918912 23 Sep 08:41 hubhenge_img14.png
 4633415 23 Sep 08:41 hubhenge_img2.png
  688083 23 Sep 08:41 hubhenge_img3.jpg
 1051643 23 Sep 08:41 hubhenge_img4.png
 3085418 23 Sep 08:41 hubhenge_img5.bin      <----
 4773183 23 Sep 08:41 hubhenge_img6.png
  666655 23 Sep 08:41 hubhenge_img7.jpg
 1018979 23 Sep 08:41 hubhenge_img8.png
   35701 23 Sep 08:41 hubhenge_img9.png
```

**Comment by netpro2k** [comment]
Will test your scene out tomorrow more in depth but I pushed some changes to that branch earlier today that might fix this (I cleaned up all the HDR image handling code so that its all the same codepath and all also handles SDR images)

**Comment by rawnsley** [comment]
@netpro2k Confirmed fixed by those changes :-) Feel free to close or leave it open until you merge the PR.
