### ISSUE TITLE
Background color isn't interpreted correctly

### ISSUE THREAD

**Issue by rawnsley** [MozillaReality/hubs-blender-exporter#42]
There's a mismatch between how the background color looks in Blender and how it looks in Hubs, particularly for dark colors. I presume it's an RGB / sRGB thing, but I can't find a definitive reference for what color space Blender exports colors in.

<img width="911" alt="Screenshot 2021-09-23 at 11 39 40" src="https://user-images.githubusercontent.com/303516/134493846-4ebac1c5-c29a-472f-bd3e-5c4e294948e7.png">

**Comment by camelgod** [comment]
@rawnsley Is the background color still wrong with Blender Filmic after the Tone Mapping changes from 0.0.13? I think the Blender Filmic should give proper tone map now.

**Comment by rawnsley** [comment]
> @rawnsley Is the background color still wrong with Blender Filmic after the Tone Mapping changes from 0.0.13? I think the Blender Filmic should give proper tone map now.

I don't think it was a tone mapping problem originally; probably a question of linear vs sRGB. I'll check next time I'm in Blender mode.

**Comment by Exairnous** [comment]
I believe that the issue is the exporter is storing the color in linear, but Hubs is reading it as sRGB.  This also affects the fog color, and will affect the mirror component when it's added.

@netpro2k @keianhzo This should be a pretty easy fix, but somebody needs to decide whether it's Hubs that should be reading colors from glTF files in linear space or if the exporter should be writing out the colors as sRGB.

**Comment by keianhzo** [comment]
I think we should probably used "COLOR_GAMMA" in all color properties to get gamma corrected values when exporting. Hex colors are gamma corrected in Blender but are stored internally as linear. When exporting Hubs expects sRGB but unless we use "COLOR_GAMMA" we are exporting linear values.

**Comment by Exairnous** [comment]
I think that's just converting it from a 0-1 float into a hex color, so to fix you'd need to convert the linear color to sRGB and then convert it to hex.

**Comment by keianhzo** [comment]
We need to do a linear to sRGB conversion here:
https://github.com/MozillaReality/hubs-blender-exporter/blob/0c593374c01506ee7fdf1963a68c5cc998c8c6fb/addons/io_hubs_addon/io/utils.py#L300
I have a fix, I'll push a PR.

**Comment by Exairnous** [comment]
I tried COLOR_GAMMA after you mentioned it, but I'm pretty sure there wasn't any change.
