### ISSUE TITLE
Video texture source/target not working in v.0.0.12

### ISSUE THREAD

**Issue by DaveyDangerpants** [MozillaReality/hubs-blender-exporter#43]
The video texture source and target components don't seem to be working with the latest version of the exporter (v.0.0.12)
[vidTexTest01.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/7264207/vidTexTest01.zip)
The model I've attached was created in Blender 2.93 and exported using v.0.0.12 of the exporter add-on. 

When added to a scene in Spoke, it does not work. I have ensured that I've included the camera on export from Blender. It would appear that the camera is not being exported, despite that being enabled through the exporter settings.

**Comment by matthewbcool** [comment]
I was able to reproduce.
`console.js:35 Error inflating gltf component "video-texture-srcEl": Couldn't find srcEl entity with index [object Object] `
