### ISSUE TITLE
Recreate duck example

### ISSUE THREAD

**Issue by nnnnnhal** [MozillaReality/hubs-blender-exporter#50]
When importing the DuckMesh to Blender and reexporting changing nothing but making sure hubs and custom properties are checked swapping the duck mesh no longer retains the quack attribute.

Workflow:
Import src/assets/models/DuckyMesh.glb into blender
Export glb with hubs and custom properties checked
Edit src/message-dispatch.js and replace path for ducky mesh
Edit src/gltf-component-mappings.js
search for AFRAME.GLTFModelPlus.registerComponent("duck", "duck", el => 
Add a debugger or console log
Reload app
type /duck into chat message
If you exported correctly a duchmesh will appear, but the quack attribute will not be attached since it did not trigger the registerComponent step

I see all of the options in the object add popout, but none seem to fix this

**Comment by nnnnnhal** [comment]
cross post'n for answer
https://github.com/mozilla/hubs/discussions/4769
Its blenders behavior of the text field, not a bug here

**Comment by keianhzo** [comment]
GLB import does not currently support components import. There is an open PR that adds support for this and will be available in the near future.
