### ISSUE TITLE
The UV scroll settings are applied to any object using that texture

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/hubs-blender-exporter#60]
STRs:
- Add a UV scroll component to an object
- Add another object and use the same material but don't add the UV scroll component
- Load in hubs and observe the result

[uv_scroll_test.zip](https://github.com/MozillaReality/hubs-blender-exporter/files/7802069/uv_scroll_test.zip)

**Comment by rawnsley** [comment]
Related to this: why is the UV scroll component applied to objects (nodes) and not to materials? It seems the wrong way around.

**Comment by keianhzo** [comment]
Closing as this has been already fixed.

@rawnsley I think in practice that gets applied to all objects using that material so it would make sense to make it a material component. I'll open an issue for that.
