### ISSUE TITLE
Existing lightmaps (exported Dec 2021) now prevent Hubs Scene from loading 

### ISSUE THREAD

**Issue by sophiedixon** [MozillaReality/hubs-blender-exporter#66]
I created a Hubs scene using Spoke at the end of 2021. The main model used the blender exporter to add a separate lightmap and texture file:

![image](https://user-images.githubusercontent.com/17412463/160677498-5e88e745-67ea-42f8-a127-033f954e6123.png)

The Hubs scene created using this method worked perfectly in December 2021.

In March 2022 I visited the Hubs scene via the same url and noticed it would no longer load. Instead, it was stuck with a message reading 'loading objects 1/2'

I tracked the issue down to the main model. When this was removed from Spoke the Hubs scene (now republished) loaded again. I then tried keeping the main model and removing the materials. I found that the scene would also load once republished from Spoke.

I then downloaded the .glb model from the original Spoke project, reopened in Blender and used the latest version of Blender Exporter and Blender to reconnect the lightmaps and textures as per the previous image.

It seems that this model, when re-exported from Blender, uploaded to Spoke, and republished, will now open as a Hubs Scene via a url. 

Although it seems the problem is fixed it's concerning that the Hubs Scene stopped loading and required a fair amount of work to update. It would be good to know why this has happened to mitigate against the same problem occurring in the future.

**Comment by keianhzo** [comment]
Can you please attach a test case Blend file here so we can take a look?
