### ISSUE TITLE
Component Mapping Properties Unknown or Undefined after Exporter Update

### ISSUE THREAD

**Issue by aelainelong** [MozillaReality/hubs-blender-exporter#73]
**Description**
After updating to the latest release of the Hubs Blender Exporter (v1.0.0b), exported .glb files that were previously working in Hubs are now triggering schema warnings around some unknown properties if the 'Environment Settings' component is in use, as well as a blocking `TypeError` when trying to read an `id` property within the Hubs component mappings.

These errors are preventing the newly exported .glb from loading in Hubs.

**Note:** I did try removing the 'Environment Settings' component and then re-adding it, but the schema warnings persist. And I don't think the 'id' property error is necessarily related to the 'Environment Settings' component, since removing that component doesn't appear to have any impact on that blocking error.

**To Reproduce**

1. Update to the latest version of the Hubs Blender Exporter
2. Open up a .blend scene that uses the Hubs 'Environment Settings' component (and which you have previously confirmed to be working in Hubs), and attempt to re-export the scene to .glb
3. Go to an existing Hubs room URL w/ `?debugLocalScene` appended to the end of the url, enter the room and attempt to drop in your newly exported .glb file. 
4. In the browser console, note any errors related to the `backgroundTexture` or `envMapTexture` properties, as well as a TypeError regarding an undefined `id` property.
5. Remove the 'Environment Settings' Hubs component from the Blender scene and then try re-exporting.
6. Note that the environment settings schema warnings now go away, but the undefined `id` error message still persists.

**Expected behavior**
.glb files exported via the Hubs Blender Exporter should load without error when brought into Hubs.

**Screenshots**
![image](https://user-images.githubusercontent.com/22333370/176217396-096dd88c-6b41-4c90-8c54-ffd22146cb55.png)

![image](https://user-images.githubusercontent.com/22333370/176214886-072fdf3c-77e6-4c20-b0bc-a2dc96ea9e1f.png)

**Hardware** 
 - Add-on Release Version: v1.0.0b
 - Blender Version: v3.2.0

**Comment by keianhzo** [comment]
Thanks for the detailed report. I have been testing with a quite complex scene that I have that has lightmaps, environment map settings and multiple components in Blender 3.2.0 but I couldn't reproduce this issue. Could you share that or a similar scene that triggers the issue here so we can check it out? That would help track down the issue. Also, is that happening only in 3.2.0 or also in previous Blender versions?

**Comment by aelainelong** [comment]
@keianhzo Thanks for taking a look and confirming! I tried uninstalling the exporter and reinstalling it again, and it appears that the exported files are now working as expected in Hubs. So this must have just been an isolated issue with my exporter install. We can close this out.
