### ISSUE TITLE
Typo:  'Frustrum' should be 'Frustum'

### ISSUE THREAD

**Issue by j-conrad** [MozillaReality/hubs-blender-exporter#77]
**Description**
The Frustum component is mislabeled 'frustrum' (additional 'R')

**Screenshots**
![Frustum1](https://user-images.githubusercontent.com/31968496/177640041-58c39f30-9583-4709-9abb-4fd48317c983.png)
![Frustum2](https://user-images.githubusercontent.com/31968496/177640043-b22c6ee5-77e1-40d3-b8e4-5c85d6376236.png)

**Hardware** 
 - Add-on Release Version: 1.0.0
 - Blender Version: 3.1.2

**Comment by rawnsley** [comment]
That one's on me sorry! I could have sworn it had an R in it 😳

**Comment by netpro2k** [comment]
haha I spelled/pronounced it this way for many years... Apparently we are not alone https://en.wikipedia.org/wiki/Frustum#Notes

**Comment by keianhzo** [comment]
Fixed by https://github.com/MozillaReality/hubs-blender-exporter/pull/117
