### ISSUE TITLE
Gizmos don't update on bone duplication.

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#83]
**Description**
When you duplicate a bone in edit mode, no gizmo is added.

**To Reproduce**
- Add an armature.
- Add a Waypoint component to the bone.
- Enter edit mode.
- Duplicate the bone.

**Expected behavior**
The gizmo should be duplicated with the bone.

**Comment by keianhzo** [comment]
Closed by https://github.com/MozillaReality/hubs-blender-exporter/pull/90
