### ISSUE TITLE
Gizmos don't display properly when there are duplicate bone names in the blend file

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#84]
**Description**
If you duplicate an armature with gizmos the gizmos won't show up on the duplicated object.

**To Reproduce**
- Add an armature.
- Add a Waypoint component to the bone.
- Duplicate the armature and move it to a new location.

**Expected behavior**
The gizmo should be duplicated with the bone.

**Comment by keianhzo** [comment]
Closed by https://github.com/MozillaReality/hubs-blender-exporter/pull/90
