### ISSUE TITLE
Gizmos on bones on other armatures don't show up correctly when in edit mode

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#85]
**Description**
If you enter edit mode on one armature all the gizmos on other armatures will disappear.

**To Reproduce**
- Add an armature.
- Duplicate the armature and move it to a new location.
- Rename the bone in the new armature to a unique name.
- Add a Waypoint component to both bones.
- Enter edit mode on one of the armatures.

**Expected behavior**
The gizmos should show on both bones.

**Comment by keianhzo** [comment]
Closed by https://github.com/MozillaReality/hubs-blender-exporter/pull/90
