### ISSUE TITLE
Gizmo disappears on host rename

### ISSUE THREAD

**Issue by Exairnous** [MozillaReality/hubs-blender-exporter#86]
**Description**
Renaming the object/bone the gizmo is attached to causes the gizmo to disappear.

**To Reproduce**
- Add an object.
- Add a Waypoint component to the object.
- Rename the object.

**Expected behavior**
The gizmo should remain visible on the object.

**Comment by keianhzo** [comment]
Closed by https://github.com/MozillaReality/hubs-blender-exporter/pull/90
